services:
  - type: web
    name: line-translate-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: RAPIDAPI_KEY
        sync: false 